version: "3"
services:

  runner:
    container_name: gitlab-cicd_runner
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    volumes:
      - './gitlab-runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      main:
        aliases:
          - runner


networks:
  main:
    external:
      name: gitlab_network
    # driver: bridge